stages:
  - test
  - build
  - deploy

lint:
  interruptible: true
  stage: test
  image: node:15.8.0-alpine3.12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn lint
    - yarn tsc

build docker image:
  interruptible: true
  stage: build
  only:
    - develop
    - staging
    - master
  image: docker:20.10.2
  services:
    - docker:20.10.2-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "VERCEL_GITLAB_COMMIT_SHA=$CI_COMMIT_SHA" >> .env
    - docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy to swarm dev:
  stage: deploy
  only:
    - develop
  variables:
    ENVIRONMENT: dev
  trigger:
    project: uptime99/devops/landing
    branch: master

deploy to swarm stg:
  stage: deploy
  only:
    - staging
  variables:
    ENVIRONMENT: stg
  trigger:
    project: uptime99/devops/landing
    branch: master

deploy to swarm prod:
  stage: deploy
  only:
    - master
  variables:
    ENVIRONMENT: prod
  trigger:
    project: uptime99/devops/landing
    branch: master
